### ISSUE TITLE
Can I customize indentation for 'for' loops?

### ISSUE THREAD

**Issue by deescuderoo** [ThibautVerron/magma-mode#16]
By modifying the variables magma-indent-args and -basic I could get an indentation of two spaces in almost all scenarios. However, this doesn't hold with the for loops. How can I set the indentation within for loops to be 2? 

Thanks!

**Comment by ThibautVerron** [comment]
Hello, thanks for the heads up!

There is/was a bug with the indentation below `while`, which was always using 6 spaces instead of 4 (in other words, it was using the length of the keyword instead of the set indent amount). It is normally fixed, but I didn't push the changes yet because it seems to break some tests for some reason.

Your problem with `for` might be similar, I will have a look and push the development branch. 

Did you install the mode through git or with melpa?

**Comment by ThibautVerron** [comment]
As I suspected this bug was already fixed in my working copy.

I still have to understand this problem with the tests, but for now I have pushed the development branch. If you have obtained the mode through git, please check out this branch and the bug should be fixed.

If you have obtained the mode through melpa, please give me a few days.

**Comment by ThibautVerron** [comment]
Bugfix commit: 6286d2148957afd93a0a44ac74af8a4f3eaa37b5

**Comment by ThibautVerron** [comment]
The changes have been pushed to the main branch, melpa should fetch the updated version in a couple of days.
